
export const dialogDefault = {
    open: false,
    id: 0,
};

export const catalogsName = 'catalogs';

export const DIALOG_AREAPRODUCT = 'DIALOG_AREAPRODUCT';

export const DIALOG_PERCAPITA = 'DIALOG_PERCAPITA';
export const DIALOG_CUSTOMER = 'DIALOG_CUSTOMER';

export const OPEN_DIALOG_BENEFICIARY = 'OPEN_DIALOG_BENEFICIARY';
export const CLOSE_DIALOG_BENEFICIARY = 'CLOSE_DIALOG_BENEFICIARY';

export const DIALOG_INPUTPRODUCT = 'DIALOG_INPUTPRODUCT';
export const DIALOG_OUTPUTPRODUCT = 'DIALOG_OUTPUTPRODUCT';
export const DIALOG_PRODUCT = 'DIALOG_PRODUCT';

export const DIALOG_WORKORDER = 'DIALOG_WORKORDER';
export const DIALOG_WORKORDERS = 'DIALOG_WORKORDERS';
export const DIALOG_PRIVATEWORKORDER = 'DIALOG_PRIVATEWORKORDER';

export const GET_CATALOGS = 'GET_CATALOGS';
export const DIALOG_TRANSFER = 'DIALOG_TRANSFER';
export const DIALOG_TRANSFER_WITHPRODUCT = 'DIALOG_TRANSFER_WITHPRODUCT';

export const OPEN_DIALOG_SERVICETEST = 'OPEN_DIALOG_SERVICETEST';
export const CLOSE_DIALOG_SERVICETEST = 'CLOSE_DIALOG_SERVICETEST';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const DIALOG_REGISTER = 'DIALOG_REGISTER';
export const DIALOG_PURCHASE = 'DIALOG_PURCHASE';
export const DIALOG_TRASLATE = 'DIALOG_TRASLATE';